// Natural Earth land outlines (world-atlas 50m) for the visible hemisphere around Arabia.
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoDistance } from "d3-geo";

const land = feature(JSON.parse(readFileSync("node_modules/world-atlas/land-50m.json", "utf8")), "land");
const centre = [47.5, 23.5];
const maxAngle = (100 * Math.PI) / 180;
const lines = [];
const geometries = land.features ? land.features.map((f) => f.geometry) : [land.geometry];
const polygons = geometries.flatMap((g) => (g.type === "Polygon" ? [g.coordinates] : g.coordinates));
for (const polygon of polygons) {
  for (const ring of polygon) {
    let run = [];
    for (const [lon, lat] of ring) {
      if (geoDistance(centre, [lon, lat]) < maxAngle) run.push([+lon.toFixed(2), +lat.toFixed(2)]);
      else { if (run.length > 1) lines.push(run); run = []; }
    }
    if (run.length > 1) lines.push(run);
  }
}
const points = lines.reduce((n, l) => n + l.length, 0);
writeFileSync("assets/map/coastlines-50m.js", `// Natural Earth 4.1.0 via world-atlas (public domain). Generated by scripts/coastlines.mjs\nwindow.COASTLINES = ${JSON.stringify(lines)};\n`);
console.log(`${lines.length} lines, ${points} points`);
